### ISSUE TITLE
Compilation Error using v1.1.0 and Arduino IDE 2.3.6

### ISSUE THREAD

**Issue by Drack714** [jvpernis/esp32-ps3#94]
I have been attempting to get a script to compile in Arduino IDE 2.3.6 using the PS3 Controller Host library v1.1.0 and receive the following comp. error:

Arduino\libraries\PS3_Controller_Host\src\ps3.c: In function 'ps3SetBluetoothMacAddress':
Arduino\libraries\PS3_Controller_Host\src\ps3.c:287:5: error: implicit declaration of function 'esp_base_mac_addr_set' [-Wimplicit-function-declaration]
  287 |     esp_base_mac_addr_set(base_mac);
      |     ^~~~~~~~~~~~~~~~~~~~~
exit status 1

Compilation error: exit status 1

Any help would be appreciated.

**Comment by ymartoglioo** [comment]
Look at this PR : https://github.com/jvpernis/esp32-ps3/pull/91/files
You'd probably need this one too : https://github.com/jvpernis/esp32-ps3/pull/55/files
