### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by welverin** [jvpernis/esp32-ps3#27]
Hi,
I just download the library and try to compile with Arduino IDE 1.8.13 and esp32 but found many undefined reference 

libraries/esp32-ps3-master/ps3_gap.c.o:(.literal.ps3_gap_init_service+0x1c): undefined reference to `GAP_ConnOpen'
libraries/esp32-ps3-master/ps3_gap.c.o:(.literal.ps3_gap_event_handle+0xc): undefined reference to `GAP_ConnGetL2CAPCid'
libraries/esp32-ps3-master/ps3_gap.c.o:(.literal.ps3_gap_event_handle+0x10): undefined reference to `GAP_ConnBTRead'
libraries/esp32-ps3-master/ps3_gap.c.o:(.literal.ps3_gap_send_hid+0x14): undefined reference to `GAP_ConnBTWrite'
libraries/esp32-ps3-master/ps3_gap.c.o: In function `ps3_gap_init_service':
/Users/leo/Documents/Arduino/libraries/esp32-ps3-master/src/ps3_gap.c:60: undefined reference to `GAP_ConnOpen'
libraries/esp32-ps3-master/ps3_gap.c.o: In function `ps3_gap_update_connected':
/Users/leo/Documents/Arduino/libraries/esp32-ps3-master/src/ps3_gap.c:60: undefined reference to `GAP_ConnGetL2CAPCid'
/Users/leo/Documents/Arduino/libraries/esp32-ps3-master/src/ps3_gap.c:60: undefined reference to `GAP_ConnGetL2CAPCid'
libraries/esp32-ps3-master/ps3_gap.c.o: In function `ps3_gap_event_handle':
/Users/leo/Documents/Arduino/libraries/esp32-ps3-master/src/ps3_gap.c:60: undefined reference to `GAP_ConnBTRead'
libraries/esp32-ps3-master/ps3_gap.c.o: In function `ps3_gap_send_hid':
/Users/leo/Documents/Arduino/libraries/esp32-ps3-master/src/ps3_gap.c:103: undefined reference to `GAP_ConnBTWrite'
collect2: error: ld returned 1 exit status
exit status 1
Errore durante la compilazione per la scheda Node32s.

**Comment by welverin** [comment]
found an answer on issue #26
